### ISSUE TITLE
Mismatch in code and documentation

### ISSUE THREAD

**Issue by mike820324** [saghul/evergreen#14]
Hi,
Just find out that in your documentation, the design part, it mentioned that the Task class is implemented using the greenlet library.
But in the tasks.py, the Task class is using python-fibers instead of greenlet.
I think some people will be confused when reading the document and tracing the source code.
Just to notify this small issue, not sure it is the right place to report this.

**Comment by saghul** [comment]
Hi!

Thanks for the report! I fixed it in https://github.com/saghul/evergreen/commit/86cd67c2c2597e461d1d509f9fcf7850fbefa2e8 and https://github.com/saghul/evergreen/commit/2f74fec4cc37f5d26a1e9b7aea912d39d8cad23e

The html in readthedocs will be regenerated with the next release.
